services:
  proxy:
    image: proxy
    build: ./proxy
    container_name: proxy
    depends_on:
      - devblog_staging_client
    volumes:
      - /home/devmaster/app/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/andrewtest.org:/etc/ssl/certs/andrewtest.org
    restart: on-failure
    ports:
      - 443:443

  devblog_staging_client:
   image: andrewtest.org_client
   build: ./client
   container_name: andrewtest.org_client
   restart: on-failure
   volumes:
     - ./client/dist:/app
     - ./client/nginx.conf:/etc/nginx/nginx.conf
     - /etc/ssl/certs/andrewtest.org:/etc/ssl/certs/andrewtest.org
   ports:
     - 8082:443