services:
  proxy:
    image: proxy
    build: ./proxy
    container_name: proxy
    depends_on:
      - devblog_client
    volumes:
      - /home/devmaster/app/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/${DEVBLOG_CERT_NAME}:/etc/ssl/certs/${DEVBLOG_CERT_NAME}
    restart: on-failure
    ports:
      - 443:443

  devblog_client:
   image: ${DEVBLOG_CONTAINER_NAME}
   build: ./client
   container_name: ${DEVBLOG_CONTAINER_NAME}
   restart: on-failure
   volumes:
     - ./client/dist:/app
     - ./client/nginx.conf:/etc/nginx/nginx.conf
     - /etc/ssl/certs/${DEVBLOG_CERT_NAME}:/etc/ssl/certs/${DEVBLOG_CERT_NAME}
   ports:
     - 8082:443