services:
  proxy:
    image: ${PROXY_CONTAINER_NAME}
    build: ./proxy
    container_name: ${PROXY_CONTAINER_NAME}
    depends_on:
      - devblog_client
    volumes:
      - ${PROXY_CONFIG_VOLUME}
      - ${CLIENT_SSL_VOLUME}
    restart: on-failure
    ports:
      - ${SSL_PORTS}

  devblog_client:
   image: ${DEVBLOG_CONTAINER_NAME}
   build: ./client
   container_name: ${DEVBLOG_CONTAINER_NAME}
   restart: on-failure
   volumes:
     - ${CLIENT_WASM_VOLUME}
     - ${CLIENT_CONFIG_VOLUME}
     - ${CLIENT_SSL_VOLUME}
   ports:
     - ${CLIENT_PORTS}