services:
  devblog_client:
   image: ${DEVBLOG_CLIENT_CONTAINER_NAME}
   build: ./client
   container_name: ${DEVBLOG_CLIENT_CONTAINER_NAME}
   restart: on-failure
   volumes:
     - ${CLIENT_WASM_VOLUME}
     - ${CLIENT_NGINX_CONFIG_VOLUME}
     - ${CLIENT_SSL_VOLUME}
   ports:
     - ${CLIENT_PORTS}
   networks:
    devblog-network:
     ipv4_address: ${CLIENT_IP_ADDRESS}
  
  devblog_server:
   image: ${DEVBLOG_SERVER_CONTAINER_NAME}
   build: ./server
   container_name: ${DEVBLOG_SERVER_CONTAINER_NAME}
   environment: 
     - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERT_PASSWORD}
     - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_CERT_PATH}
     - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}
   volumes:
     - ${SERVER_PUBLISH_VOLUME}
     - ${SERVER_HTTPS_VOLUME}
     - ${SERVER_APPSETTINGS_VOLUME}
   ports:
     - ${SERVER_PORTS}
   networks:
    devblog-network:
      ipv4_address: ${SERVER_IP_ADDRESS}

  devblog_proxy:
    image: ${DEVBLOG_PROXY_CONTAINER_NAME}
    build: .
    container_name: ${DEVBLOG_PROXY_CONTAINER_NAME}
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/${DEVBLOG_CERT_NAME}:/etc/ssl/certs/${DEVBLOG_CERT_NAME}
    restart: on-failure
    ports:
      - ${PROXY_PORTS_1}
      - ${PROXY_PORTS_2}
    networks:
      devblog-network:
        ipv4_address: ${PROXY_IP_ADDRESS}
    depends_on:
      - devblog_client
      - devblog_server

networks:
  devblog-network:
    name: ${DEVBLOG_NETWORK}
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
