services:
  proxy:
    image: ${PROXY_CONTAINER_NAME}
    build: ./proxy
    container_name: ${PROXY_CONTAINER_NAME}
    depends_on:
      - devblog_client
      - devblog_server
    volumes:
      - ${PROXY_NGINX_CONFIG_VOLUME}
      - ${CLIENT_SSL_VOLUME}
    restart: on-failure
    ports:
      - ${SSL_PORTS}
    networks:
      mynet:
        ipv4_address: ${PROXY_IP_ADDRESS}

  devblog_client:
   image: ${DEVBLOG_CLIENT_CONTAINER_NAME}
   build: ./client
   container_name: ${DEVBLOG_CLIENT_CONTAINER_NAME}
   restart: on-failure
   volumes:
     - ${CLIENT_WASM_VOLUME}
     - ${CLIENT_NGINX_CONFIG_VOLUME}
     - ${CLIENT_SSL_VOLUME}
   ports:
     - ${CLIENT_PORTS}
   networks:
    mynet:
     ipv4_address: ${CLIENT_IP_ADDRESS}
  
  devblog_server:
   image: ${DEVBLOG_SERVER_CONTAINER_NAME}
   build: ./server
   container_name: ${DEVBLOG_SERVER_CONTAINER_NAME}
   environment: 
     - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERT_PASSWORD}
     - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_CERT_PATH}
     - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}
   volumes:
     - ${SERVER_PUBLISH_VOLUME}
     - ${SERVER_HTTPS_VOLUME}
     - ${SERVER_APPSETTINGS_VOLUME}
   ports:
     - ${SERVER_PORTS}
   networks:
    mynet:
      ipv4_address: ${SERVER_IP_ADDRESS}

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
