# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - thedevblog

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Build with dotnet
      working-directory: 'Dev-Blog/BlazorServer'
      run: dotnet build --configuration Release

    - name: dotnet publish
      working-directory: 'Dev-Blog/BlazorServer'
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/BlazorServer

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thedevblog'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a27835ee2e1b44158e18d43945373a3b }}
        package: ${{env.DOTNET_ROOT}}/BlazorServer
